version: '3'


services:
  redis:
    image: "redis/redis-stack:latest"
    ports:
      - "6379:6379"
      - "8001:8001"
  datastore:
    build: .
    image: redisearch_demo
    links:
      - "redis:redis"
    ports:
      - "8080:8080"
    environment:
        - REDIS_SERVER=redis
        - REDIS_PORT=6379